### ISSUE TITLE
Wrapper component for embedding an Observable notebook

### ISSUE THREAD

**Issue by jamesscottbrown** [Greater-London-Authority/ldn-viz-tools#110]
After the ~~Civic Strength Index~~ Wellbeing Sustainability Measure project is completed, consider whether we can abstract the code that was written to embed Observable notebooks in order to create a reusable component.

**Comment by jamesscottbrown** [comment]
The relevant code is: https://github.com/Greater-London-Authority/app-wellbeing-sustainability-measure/blob/d59d483115a2ed13e04fef23a230f10e1791e6c8/src/lib/components/dataExplorer/DataExplorer.svelte#L6

**Comment by ChrisKnightLDN** [comment]
was this addressed in #181 ?

**Comment by jamesscottbrown** [comment]
> was this addressed in #181 ?

No - #181 allows embedding an Observable Plot plot in a Svelte project that uses our component library, whereas this PR is about embedding an Observable Notebook (or specific cells from a notebook).

However, I'm not sure this is something we'll actually want to do in future (especially now that Observable Framework provides an additional publication route).
