### ISSUE TITLE
replace svelte-heroicons

### ISSUE THREAD

**Issue by ChrisKnightLDN** [Greater-London-Authority/ldn-viz-tools#134]
the svelte-heroicons package that we have been using does not seem to be updated and is already missing some icons. There are plenty of other implementations of hero-icon package for svelte - so we should swap out for a more actively maintained package

**Comment by jamesscottbrown** [comment]
It also has a `peerDependency` on Svelte that doesn't cover Svelte 4, so it's necessary to either run `npm isntall` with the `--force` option or add an `override` to `package.json`.
