### ISSUE TITLE
Components using '$app/...' should be refactored

### ISSUE THREAD

**Issue by ChrisKnightLDN** [Greater-London-Authority/ldn-viz-tools#202]
Components assuming the availibility of '$app/...' cause issues in non sveltekit apps (ie. storybook): Cannot read properties of undefined (reading 'url').

see: https://kit.svelte.dev/docs/packaging#best-practices

"You should avoid using [SvelteKit-specific modules](https://kit.svelte.dev/docs/modules) like $app in your packages unless you intend for them to only be consumable by other SvelteKit projects. E.g. rather than using import { browser } from '$app/environment' you could use import { BROWSER } from 'esm-env' ([see esm-env docs](https://github.com/benmccann/esm-env)). You may also wish to pass in things like the current URL or a navigation action as a prop rather than relying directly on $app/stores, $app/navigation, etc. Writing your app in this more generic fashion will also make it easier to setup tools for testing, UI demos and so on."

**Comment by jamesscottbrown** [comment]
This was resolved in #289
