### ISSUE TITLE
Create sveltekit starter template for projects

### ISSUE THREAD

**Issue by ChrisKnightLDN** [Greater-London-Authority/ldn-viz-tools#23]
A consolidated starter template pre packed with our stack. Tailwind, static adaptors, prettier config, vitest etc. TBD.

**Comment by ChrisKnightLDN** [comment]
Also need to add Roboto font in head

**Comment by jamesscottbrown** [comment]
Should also include a YAML metadata block with the standard headers in the README, so new projects get listed correctly in the [app index](https://github.com/greater-London-Authority/app-index).
