### ISSUE TITLE
Input component does not grey out text when disabled

### ISSUE THREAD

**Issue by PaulioRandall** [Greater-London-Authority/ldn-viz-tools#370]
**Describe the bug**

`<Input disabled />` does not have greyed out text when disabled so it looks editable. However, the input label is greyed out.

**To Reproduce**

Write the following Svelte code:

```js
import { Input } from '@ldn-viz/ui'

<Input name="meh" value="some text" disabled />
```

**Expected behavior**

The input text should be greyed out the same as the label text.

**Comment by jamesscottbrown** [comment]
The input box itself is greyed out: if the text inside the box was also greyed out it would be difficult to provide enough contrast between the text and background.

How the component currently looks in the disabled state:
![Screenshot 2024-06-26 at 12 10 18](https://github.com/Greater-London-Authority/ldn-viz-tools/assets/338833/12ff4907-4e8e-490a-ad9f-fddab6e8057d)

**Comment by PaulioRandall** [comment]
> The input box itself is greyed out: if the text inside the box was also greyed out it would be difficult to provide enough contrast between the text and background.
> 
> How the component currently looks in the disabled state: ![Screenshot 2024-06-26 at 12 10 18](https://private-user-images.githubusercontent.com/338833/343132321-12ff4907-4e8e-490a-ad9f-fddab6e8057d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0MDE2OTIsIm5iZiI6MTcxOTQwMTM5MiwicGF0aCI6Ii8zMzg4MzMvMzQzMTMyMzIxLTEyZmY0OTA3LTRlOGUtNDkwYS1hZDlmLWZkZGFiNmU4MDU3ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNlQxMTI5NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02OTllZmE3Mzc4ZWYyOTlmNjY5NjVhMzkzMmMxM2EwZTVkNGU5ZTVmNGI4NjRiODgxYTdmNGRiZjg5OTRlM2U3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BQeLPUKcY98M6uqRbQu8Ub2RcMQAdSl5J5iTL4lVnDY)

In my case, low contrast is intended for disabled state. The content is irrelevant to the user (has no bearing on the final submission) if the input has been disabled. I don't delete the disabled content until they click _'continue'_ in case the user has a sudden change of heart. 

![image](https://github.com/Greater-London-Authority/ldn-viz-tools/assets/29413800/4d741d2a-5a3d-42d1-8e6d-de7d63d4dae7)

While this gives the impression the content is irrelevant but the user can see that they won't have to re-enter the information if they have a change of heart:
![image](https://github.com/Greater-London-Authority/ldn-viz-tools/assets/29413800/c2d6b824-7e0a-486a-94e1-5874ca1f6db2)

Perhaps another prop?

**Comment by jamesscottbrown** [comment]
In the storybook stories [1], it looks like in the dark theme the text color should already be changing when the input is disabled:

Enabled:

![image](https://github.com/Greater-London-Authority/ldn-viz-tools/assets/338833/d6cc4402-b6ec-48b8-a6e5-f6007b99f7a4)


Disabled:

![image](https://github.com/Greater-London-Authority/ldn-viz-tools/assets/338833/f93c8b78-ab78-4ade-ae67-5c3f36844f97)

(this looks slightly odd as Storybook toggles the light/dark theme but doesn't change the background color behind the component)

[1]: https://greater-london-authority.github.io/ldn-viz-tools/?path=/docs/ui-input--documentation&globals=theme:dark

**Comment by ChrisKnightLDN** [comment]
line 149 of input targets: `$$restProps.disabled ? 'cursor-not-allowed' : ''` in next I have updated this to `$$restProps.disabled || disabled ? 'cursor-not-allowed text-color-input-label-disabled' : '',` (bing the correct color token)

This resolves the issue - but I'm not 100% why we target $$restProps.disabled rather than just disabled?

![Screenshot 2024-08-05 at 15 09 08](https://github.com/user-attachments/assets/a6cc1fc5-3434-4f82-9864-d3546ecc1743)
![Screenshot 2024-08-05 at 15 09 27](https://github.com/user-attachments/assets/156b35c4-086b-4549-b84d-3af8bcb8f4ca)

**Comment by PaulioRandall** [comment]
> line 149 of input targets: `$$restProps.disabled ? 'cursor-not-allowed' : ''` in next I have updated this to `$$restProps.disabled || disabled ? 'cursor-not-allowed text-color-input-label-disabled' : '',` (being the correct color token)
> 
> This resolves the issue - but I'm not 100% why we target $$restProps.disabled rather than just disabled?
> 
> ![Screenshot 2024-08-05 at 15 09 08](https://private-user-images.githubusercontent.com/111759008/355134898-a6cc1fc5-3434-4f82-9864-d3546ecc1743.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4Njc4MTUsIm5iZiI6MTcyMjg2NzUxNSwicGF0aCI6Ii8xMTE3NTkwMDgvMzU1MTM0ODk4LWE2Y2MxZmM1LTM0MzQtNGY4Mi05ODY0LWQzNTQ2ZWNjMTc0My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNVQxNDE4MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wN2YwNjA1ZTc4OTc4YWYxYjNiYzlkZWE5NGVjYzQyNDRlNjRlY2RlNDc0ZTE5ZmIxN2EyZDIzMDZmMWM1Mzk5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Af9u6DgCpL-HOnMLnONwq_jk3aIQZEsUetWZaDcOqW8) ![Screenshot 2024-08-05 at 15 09 27](https://private-user-images.githubusercontent.com/111759008/355134902-156b35c4-086b-4549-b84d-3af8bcb8f4ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4Njc4MTUsIm5iZiI6MTcyMjg2NzUxNSwicGF0aCI6Ii8xMTE3NTkwMDgvMzU1MTM0OTAyLTE1NmIzNWM0LTA4NmItNDU0OS1iODRkLTNhZjhiY2I4ZjRjYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNVQxNDE4MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZDcwMTEyZGZjY2RmYWY5MmNhNTIzMDRlNjAwODk1YzZhN2UwNjg2ZmVlNjM2YWFiNjk0NmI3MDE3OTUzZWFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tiBo39-6UgSFw47lNVdonHHQQI2DKYIfsvKrLYsAUx4)

`$$restProps` are props passed to a component that were not explicitly defined so `$$restProps.disabled` won't exist if `export let disabled` prop exists. It should just be `disabled ? 'cursor-not-allowed text-color-input-label-disabled'`.

It's in a cloud of strings and ternary operators so I suspect it slipped past refactoring and review.

![image](https://github.com/user-attachments/assets/3717c057-0622-40fb-991e-cc1903c8d318)

**Comment by ChrisKnightLDN** [comment]
Great,  this is simplified on 'next' 
<img width="580" alt="Screenshot 2024-08-05 at 16 09 13" src="https://github.com/user-attachments/assets/528fe2d6-5f7c-47e3-b4bf-4a339e2f927c">

I can open a pr on the release branch that addresses this too.

**Comment by ChrisKnightLDN** [comment]
closing as done
