### ISSUE TITLE
Fix text color of label for Switch input in dark mode

### ISSUE THREAD

**Issue by jamesscottbrown** [Greater-London-Authority/ldn-viz-tools#392]

**Comment by ChrisKnightLDN** [comment]
this is done one the next branch

**Comment by ChrisKnightLDN** [comment]
marking as resolved: 
![Screenshot 2024-08-06 at 10 23 25](https://github.com/user-attachments/assets/dcb29212-8410-4c97-886e-b9f53c1f86c8)
