### ISSUE TITLE
Observable Plot Default Text Sizes

### ISSUE THREAD

**Issue by mikeldn** [Greater-London-Authority/ldn-viz-tools#398]
The sizing of the text in our Observable plot defaults are slightly off.

1) In the plot fragments file, default label size should be 14px (not 16px):
https://github.com/Greater-London-Authority/ldn-viz-tools/blob/b7d2989d4a75132aa95a0f2838eae1207a2bbeae/packages/charts/src/lib/observablePlotFragments/observablePlotFragments.ts#L8 

2) The plot fragments file refers to a global style of "defaultCcolorLegendLabel". This has a typo.. should be: "defaultColorLegendLabel".
https://github.com/Greater-London-Authority/ldn-viz-tools/blob/b7d2989d4a75132aa95a0f2838eae1207a2bbeae/packages/charts/src/lib/observablePlotFragments/observablePlotFragments.ts#L25

3) The ObservablePlot.svelte file contains a global style for the Color Legend Label. The class also contains the same typo, and the text size should be 16px (to match body copy) not 14px.
https://github.com/Greater-London-Authority/ldn-viz-tools/blob/b7d2989d4a75132aa95a0f2838eae1207a2bbeae/packages/charts/src/lib/observablePlot/ObservablePlot.svelte#L207 

Should these sizes also be bound to tokens rather than explicit sizes... like text-base regular  and text-sm regular ? TBD

**Comment by ChrisKnightLDN** [comment]
defaultStyle can be set to use ems based on our default font size of 16: fontSize: '0.875rem' will be 14px
