### ISSUE TITLE
Update color system notebook to import from package

### ISSUE THREAD

**Issue by jamesscottbrown** [Greater-London-Authority/ldn-viz-tools#51]
The [color system notebook](https://observablehq.com/@ldn/color-system) should import the `colors.json` file from the `@ldn-viz/themes` package as a single source-of-truth.

**Comment by jamesscottbrown** [comment]
See https://github.com/Greater-London-Authority/ldn-viz-tools/pull/185

**Comment by ChrisKnightLDN** [comment]
Closing as done
